### ISSUE TITLE
Throw errors

### ISSUE THREAD

**Issue by OliverJAsh** [richgilbank/ES6-Repl-Chrome-Extension#14]
When an error occurs, it silently fails:

![image](https://cloud.githubusercontent.com/assets/921609/4885874/a959451a-6377-11e4-9c43-ecac40938b65.png)

**Comment by richgilbank** [comment]
A little slow to take a look at this, but I finally had a chance to see what was up here. It seems that getting raw access to the page's execution context via `chrome.devtools.inspectedWindow.eval` still catches errors that occur (https://developer.chrome.com/extensions/devtools_inspectedWindow#method-eval). 

There are 2 approaches as I see it: the extension could keep doing what it's doing and just listen for exceptions which is easier and I've [pushed a fix for now](https://github.com/richgilbank/ES6-Repl-Chrome-Extension/commit/fe5ced2d04d983b888f7abe0feba8cb7b5ce3f8d). The other option would be to allow the exceptions to actually throw using native browser behaviour by executing the script a different way, one which unfortunately sandboxes things so there's no access to page JS. I tried that out too: https://github.com/richgilbank/ES6-Repl-Chrome-Extension/commit/a3ca928dcf644aa7e5638264088d770bb2423aa5. 

Any thoughts on which way is better? Or alternatives?
/cc: @UltCombo in case you have any thoughts on this.

**Comment by UltCombo** [comment]
I believe it is fine as long as the errors are logged to the console. Getting nice stack traces are usually a complete pain though (regarding sourcemaps/etc), so I usually don't mind this.
Sorry, I don't have any strong feelings in this topic. `=]`

**Comment by richgilbank** [comment]
Fixed with https://github.com/richgilbank/ES6-Repl-Chrome-Extension/commit/fe5ced2d04d983b888f7abe0feba8cb7b5ce3f8d
