### ISSUE TITLE
Add a build system

### ISSUE THREAD

**Issue by richgilbank** [richgilbank/ES6-Repl-Chrome-Extension#19]
Things are big enough that this is really necessary. Livereload and a file structure are the big requirements here, but it would be nice to be able to write in ES6 with https://www.npmjs.com/package/gulp-6to5 or similar.  
cc: @hemanth @tessalt since you're not watching the repo :stuck_out_tongue_winking_eye:

**Comment by hemanth** [comment]
:angel:

**Comment by tessalt** [comment]
:eyes:

**Comment by richgilbank** [comment]
Closed with https://github.com/richgilbank/ES6-Repl-Chrome-Extension/pull/27
