### ISSUE TITLE
Syntax highlighting for ES6

### ISSUE THREAD

**Issue by richgilbank** [richgilbank/ES6-Repl-Chrome-Extension#24]
![screen_shot_2015-02-11_at_7 38 15_pm](https://cloud.githubusercontent.com/assets/1245284/6159990/2101e89a-b22b-11e4-94f2-154731118da4.png)

**Comment by darcyclarke** [comment]
:+1: this please...

**Comment by tessalt** [comment]
Update codemirror could fix https://github.com/codemirror/CodeMirror/issues/2622

**Comment by richgilbank** [comment]
Amaze. Will npmify and bump tomorrow. Thanks!

**Comment by richgilbank** [comment]
https://github.com/richgilbank/ES6-Repl-Chrome-Extension/commit/24ac6731ebfe1a81fd09a3ad7de9a807e0f51423
