### ISSUE TITLE
Move package.json to root dir

### ISSUE THREAD

**Issue by richgilbank** [richgilbank/ES6-Repl-Chrome-Extension#32]

**Comment by richgilbank** [comment]
NPM doesn't allow custom node_modules locations, and chrome extensions can't `../` out of their directory, so I just went ahead and moved _everything_ to the root: https://github.com/richgilbank/ES6-Repl-Chrome-Extension/commit/b5a82a4e714ff0d58bc4883baac034ae4fbdb97b

**Comment by darcyclarke** [comment]
Merci
