### ISSUE TITLE
pressing ] switches from ES6Repl tab to the console tab (azerty keyboard)

### ISSUE THREAD

**Issue by cauburtin** [richgilbank/ES6-Repl-Chrome-Extension#37]
`]` is reached with Alt Gr+) on my keyboard, and it automatically switches tab view instead of writing this character. I have to copy/paste it for the moment

**Comment by richgilbank** [comment]
Interesting, thanks for reporting! I don't have an azerty keyboard around to test with, but it looks like this is [an open issue for DevTools as a whole](https://code.google.com/p/chromium/issues/detail?id=128878), which means there's not much I can do, unfortunately.
